//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product_items
    {
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public Nullable<System.DateTime> pro_posted_date { get; set; }
        public Nullable<double> pro_price { get; set; }
        public Nullable<int> pro_status { get; set; }
        public string pro_image { get; set; }
        public Nullable<int> pro_fk_ad { get; set; }
        public Nullable<int> pro_fk_cat { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
        public virtual tbl_product_category tbl_product_category { get; set; }
    }
}
